# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\everything.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 308)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_find = QtWidgets.QPushButton(Dialog)
        self.pushButton_find.setMinimumSize(QtCore.QSize(0, 5))
        self.pushButton_find.setFlat(False)
        self.pushButton_find.setObjectName("pushButton_find")
        self.gridLayout.addWidget(self.pushButton_find, 3, 1, 1, 1)
        self.listWidget_result = QtWidgets.QListWidget(Dialog)
        self.listWidget_result.setObjectName("listWidget_result")
        self.gridLayout.addWidget(self.listWidget_result, 4, 0, 1, 2)
        self.pushButton_select = QtWidgets.QPushButton(Dialog)
        self.pushButton_select.setMinimumSize(QtCore.QSize(0, 5))
        self.pushButton_select.setObjectName("pushButton_select")
        self.gridLayout.addWidget(self.pushButton_select, 1, 1, 1, 1)
        self.lineEdit_dir = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dir.setMinimumSize(QtCore.QSize(250, 35))
        self.lineEdit_dir.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.gridLayout.addWidget(self.lineEdit_dir, 1, 0, 1, 1)
        self.lineEdit_filePattern = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_filePattern.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_filePattern.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit_filePattern.setObjectName("lineEdit_filePattern")
        self.gridLayout.addWidget(self.lineEdit_filePattern, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Everything"))
        self.pushButton_find.setText(_translate("Dialog", "🔍"))
        self.pushButton_select.setText(_translate("Dialog", "浏览"))
        self.lineEdit_dir.setPlaceholderText(_translate("Dialog", "查找路径"))
        self.lineEdit_filePattern.setPlaceholderText(_translate("Dialog", "文件Pattern"))
